//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Recreation_Respite_Dashboard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Events
    {
        public int Id { get; set; }
        public string name { get; set; }
        public string location { get; set; }
        public string date { get; set; }
        public string end_date { get; set; }
        public string number_participant { get; set; }
        public string image { get; set; }
        public string description { get; set; }
    }
}
